default: &default
  pool: 5
  adapter: mysql2
  encoding: utf8
  username: root
  password: 12345678
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: quiz_now_dev

test:
  <<: *default
  database: quiz_now_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>